version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  eieimarketplace-vendor-reservation:
    container_name: eieimarketplace-vendor-reservation
    build:
      context: ../eieimarketplace-vendor-reservation
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "7003:7003"
    depends_on:
      - rabbitmq

  eieimarketplace-slip-management:
    container_name: eieimarketplace-slip-management
    build:
      context: ../eieimarketplace-slip-management
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "7004:7004"
    depends_on:
      - rabbitmq

  eieimarketplace-user-management:
    build:
      context: ../eieimarketplace-user-management
      dockerfile: supabase_dockerfile/Dockerfile
    image: supabase_user_eieimarketplace
    container_name: eieimarketplace-user-management
    restart: always
    environment:
      SUPABASE_DB_URL: ${SUPABASE_DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - "7001:7001"
    depends_on:
      - rabbitmq

  eieimarketplace-market-management:
    build:
      context: ../eieimarketplace-market-management
      dockerfile: Dockerfile
    container_name: eieimarketplace-market-management
    env_file:
      - .env
    ports:
      - "50051:50051"
      - "7002:7002"
    volumes:
      - ./app:/app
